packages:
  - "apps/*"
allowBuilds:
  "@apollo/protobufjs": false
  "@prisma/engines": true
  argon2: true
  prisma: true
  unrs-resolver: true
peerDependencyRules:
  allowedVersions:
    "@apollo/server-plugin-landing-page-graphql-playground>@apollo/server": "5"
